sudo: required
services:
  - docker

before_install:
  - docker build -t docker_react -f Dockerfile.dev .

script:
  - docker run docker_react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-083177586027xzzcx"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
